### ISSUE TITLE
DNS 验证是否可以支持cloudflare？

### ISSUE THREAD

**Issue by rememberli** [xdtianyu/scripts#10]
另外原本letsencrypt.sh是好像支持ECDSA 证书的.

**Comment by xdtianyu** [comment]
@rememberli 非常抱歉长时间没有回复这个问题。因为 cloudflare 自带了 https 证书，所以当前没有计划支持。dnspod 和 cloudxns dns验证方式的 ECDSA 配置会后续添加。
