### ISSUE TITLE
增加对Lighttpd的支持

### ISSUE THREAD

**Issue by D-L** [xdtianyu/scripts#13]
Lighttpd需要两个关键参数： `ssl.ca-file`和`ssl.pemfile`

`ssl.ca-file` = example.chained.crt 
`ssl.pemfile`需要按如下方式合并
`cat example.com.key example.crt > example.pem`
启用这个`example.pem`就好了

**Comment by xdtianyu** [comment]
已添加，欢迎测试 [README-CN](https://github.com/xdtianyu/scripts/blob/master/lets-encrypt/README-CN.md)
