### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by ky0ncheng** [xdtianyu/scripts#14]
λ  key  ./le-cloudxns.sh cloudxns.conf
# INFO: Using main config file cloudxns.conf
Processing ky0n.xyz with alternative names: www.ky0n.xyz
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for ky0n.xyz...
 + Requesting challenge for www.ky0n.xyz...
ky0n.xyz 1Woz1gb_E0zPqeMciNfme1xhl00F8rahy_9icLrKn9s ctrL-fwUFYi7-6KadeGPF2yUSj5YyZUt4Tz7ICtIO_A
./cloudxns.sh: line 24: md5sum: command not found
DOMAIN ID:
./cloudxns.sh: line 30: md5sum: command not found
RECORD ID:
./cloudxns.sh: line 44: md5sum: command not found
{"code":302,"message":"Sign illegal"}
2016年 3月14日 周一 01時21分35秒 CST -- Update failed
 + Responding to challenge for ky0n.xyz...
ERROR: Challenge is invalid! (returned: invalid) (result: {"type":"dns-01","status":"invalid","error":{"type":"urn:acme:error:connection","detail":"DNS problem: NXDOMAIN looking up TXT for _acme-challenge.ky0n.xyz"},"uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/tm8Pj1FoxFZcitPkbA7JBBDxyWhQMruc9mCRHSurJ4s/27495516","token":"1Woz1gb_E0zPqeMciNfme1xhl00F8rahy_9icLrKn9s","keyAuthorization":"1Woz1gb_E0zPqeMciNfme1xhl00F8rahy_9icLrKn9s.h6e2xziJ4qiy1QUOTt0luS5YJhM3bs59t3a9kIfkPVI"})

**Comment by xdtianyu** [comment]
这不是有提示吗 `md5sum: command not found`

**Comment by ky0ncheng** [comment]
原来如此 之前linux上可以正常签发 mac默认没有这个md5sum

thx~
