### ISSUE TITLE
如何给端口转发的域名配置证书？

### ISSUE THREAD

**Issue by hxzchina** [xdtianyu/scripts#15]
比如给deluge-webui配证书，因为是在nginx 上proxy到8112端口，没有DOMAIN_DIR，那这种怎么填？

**Comment by xdtianyu** [comment]
可以使用 `dns` 验证的方式 [https://github.com/xdtianyu/scripts/tree/master/le-dns](https://github.com/xdtianyu/scripts/tree/master/le-dns)，目前支持 `cloudxns` 和 `dnspod`

或者临时绑定一个目录验证，或者对 `deluge` 做个更完整的 `nginx` 转发，变成主 `www` 服务器的一个子目录。

**Comment by hxzchina** [comment]
用dns验证的方式报错（用的dnspod）
**Challenge is invalid! (returned: invalid) (result: {"type":"dns-01","status":"invalid","error":{"type":"urn:acme:error:unauthorized","detail":"Correct value not found for DNS challenge"},"uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/hfw51GHTI0QhdBjH5s9EIWjJjy7wq7hRmFtMKymy_Vk/27886668","token":"jnM1UbGOoS0cBnpwwOnBDuSykx4DxoJKNM6ENKNxAlY","keyAuthorization":"jnM1UbGOoS0cBnpwwOnBDuSykx4DxoJKNM6ENKNxAlY.cDH_ZqpYUQRh880WM_8c8o8eN0nRGCtyW32VZ89h3CE"})**

但是用临时绑定目录验证的方法成功解决了问题
具体是在nginx处添加了
location  / {
        root /home/wwwroot/XX.XXXX.XX;
	    }

端口转发是在
location =/  {
}处理的

）
太感谢了！

**Comment by xdtianyu** [comment]
建议把 `uri":"https://acme-v01.api.letsencrypt.org/acm` 里的私人信息编辑掉。DNS验证不过的问题需要这段前面的输出来做判断。不知道你是不是没有修改conf文件。

**Comment by hxzchina** [comment]
多谢提醒，不过由于我现在尝试了太多次，现在已经报 Too many certificates了。
可能要等下一周才能试验。
多谢。
另外临时绑定目录验证的方法应该用这种配置才能正常工作
location / {
        这里处理端口转发
	    }
location ~ /.well-known { 
	    root  /home/wwwroot/XX.XXXX.XX;}

**Comment by hxzchina** [comment]
很抱歉现在才来试验，不过还是有问题。我确认domain都填对了
下面是完整输出
# INFO: Using main config file dnspod.conf
Processing XXX.XXX.XXX
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for XXX.XXX.XXX...
XXX.XXX.XXX .....................................................
_acme-challenge.XXX.XXX.XXX

:
NEW RECORD
DNS UPDATE FAILED
 + Responding to challenge for XXX.XXX.XXX...
ERROR: Challenge is invalid! (returned: invalid) (result: {"type":"dns-01","status":"invalid","error":{"type":"urn:acme:error:unauthorized","detail":"Correct value not found for DNS challenge"},"uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/........................./33378102","token":"..............................","keyAuthorization":"......................."})

**Comment by xdtianyu** [comment]
感谢反馈。

`DNS UPDATE FAILED` 应该是域名更新出错了，不知道是不是 `dnspod` 更新了接口，注意 `TOKEN`  的格式 `TOKEN="YOUR_TOKEN_ID,YOUR_API_TOKEN"` 需要将 `TOKEN ID,` 也加入到里边。我已經更新了 [dnspod.conf](https://github.com/xdtianyu/scripts/blob/master/le-dns/dnspod.conf) 文件和 [README](https://github.com/xdtianyu/scripts/tree/master/le-dns#dnspod)

**Comment by hxzchina** [comment]
已经完美解决问题，多谢
