### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by uutan** [xdtianyu/scripts#17]
`File "/tmp/acme_tiny.py", line 31
    pub_exp = "0{0}".format(pub_exp) if len(pub_exp) % 2 else pub_exp`

SyntaxError: invalid syntax

**Comment by xdtianyu** [comment]
感谢反馈，可以提供下系统信息及 `python` 版本吗，这里来看是 `acme_tiny` 出错了

**Comment by uutan** [comment]
Python 2.4.3 (#1, Apr 14 2011, 20:41:59)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-50)] on linux2

**Comment by xdtianyu** [comment]
额，大概是因为版本太老了 `acme_tiny` 没有做兼容。

**Comment by uutan** [comment]
又来麻烦你了。
已升级了Python至2.7.2，但现在到这个错
Traceback (most recent call last):
  File "/tmp/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/tmp/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/tmp/acme_tiny.py", line 149, in get_crt
    domain, challenge_status))
ValueError: www.caoguo.com challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'url': u'http://www.caoguo.com/.well-known/acme-challenge/CVzmfInI331SkmUpuv-1gU3zQYmuXH96SyextO5V0nU', u'hostname': u'www.caoguo.com', u'addressUsed': u'115.29.243.155', u'port': u'80', u'addressesResolved': [u'115.29.243.155']}], u'keyAuthorization': u'CVzmfInI331SkmUpuv-1gU3zQYmuXH96SyextO5V0nU.t-xLIhTDY15uQYeYO8X24c_RBfiOns6O-IjxT0vztQo', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/5pu-ruhYVbRGt2Rh6zcsDNa448SVvUmt4DKhIQYgsJs/42835522', u'token': u'CVzmfInI331SkmUpuv-1gU3zQYmuXH96SyextO5V0nU', u'error': {u'type': u'urn:acme:error:connection', u'detail': u'DNS problem: query timed out looking up CAA for www.caoguo.com'}, u'type': u'http-01'}

**Comment by uutan** [comment]
感谢，已解决了。

**Comment by xdtianyu** [comment]
额，尽量不要把域名和IP信息贴出来。从上面的看应该是DNS解析的问题，你是怎么解决的呢？
