### ISSUE TITLE
 Problem connecting to server (curl returned with 7)

### ISSUE THREAD

**Issue by ChasteLove** [xdtianyu/scripts#18]
ah ,how to deal with it?

**Comment by xdtianyu** [comment]
Thanks for feedback, can you provider more information? which script and what OS are you using?

**Comment by ChasteLove** [comment]
cloudxns.conf le-cloudxns.sh  
error info:Domain locked,please unlock domain

first in other option page

该域名已被用户锁定,请先解锁

xubuntu

**Comment by xdtianyu** [comment]
建议先在 [cloudxns](www.cloudxns.net) 检查下域名的状态，先解锁下域名再试下。

**Comment by ChasteLove** [comment]
域名状态正常，也没有上锁，这个问题我再查查API看看吧，非常感谢回答！

**Comment by xdtianyu** [comment]
参考这里 https://community.letsencrypt.org/t/getting-the-client-sent-an-unacceptable-anti-replay-nonce/9172/18 应该是 le 服务端的问题，建议重试下，注意尽量不要超过一周内七次的限制

**Comment by ChasteLove** [comment]
感谢！
