### ISSUE TITLE
请问,如果有多个根域名应该怎么办?

### ISSUE THREAD

**Issue by wasas** [xdtianyu/scripts#19]
**[通过 DNS 验证方式获取 lets-encrypt 证书的快速脚本](https://github.com/xdtianyu/scripts/tree/master/le-dns)** 这个

你好, 以dnspod为例,
如果我有多个根域名,
aaa.com
11.aaa.com 22.aaa.com 33.aaa.com ....
bbb.com
11.bbb.com 22.bbb.com 33.bbb.com ....
ccc.com
11.ccc.com 22.ccc.com 33.ccc.com ....

那配置文件里应该怎么写呢?   我试过DOMAIN="aaa.com bbb.com"
还有打多行
DOMAIN="aaa.com"
DOMAIN="bbb.com"
都没法用的. 
难不成只有建立多个文件夹?

**Comment by xdtianyu** [comment]
参考 https://github.com/xdtianyu/scripts/issues/7 做多个配置文件然后脚本运行多次

**Comment by wasas** [comment]
感谢回复
呃...  我试了类似的笨方法, 就是完全复制两个文件夹, 
把 dnspod.conf   dnspod.sh   dnspod-hook.sh    le-dnspod.sh    letsencrypt.sh 这几个文件都分别复制几份,
我看这程序会自动生成 private_key.json private_key.pem domains.txt  这三个文件, 内容都还是不一样的,
那如果在同一个文件夹里用不同的 dnspod.conf 来获取, 会有什么隐患吗?

**Comment by xdtianyu** [comment]
private_key 自动生成的，如果有会重复利用。domains.txt 是中间文件，运行一次会覆盖。

**Comment by wasas** [comment]
哦.. 好的, 那基本上就没有什么隐患了, 非常感谢你的回复...
