### ISSUE TITLE
key不匹配是怎么回事？

### ISSUE THREAD

**Issue by Jaggle** [xdtianyu/scripts#20]
failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch

**Comment by xdtianyu** [comment]
请贴一下配置文件，注意掩盖敏感信息

**Comment by Jaggle** [comment]
配置文件如下：
# only modify the values, key files will be generated automaticly.
   ACCOUNT_KEY="account.key"
   DOMAIN_KEY="ch.yeskn.com.key"
   DOMAIN_DIR="我的blog根目录"
   DOMAINS="DNS:ch.yeskn.com"
   #ECC=TRUE
   #LIGHTTPD=TRUE

**Comment by xdtianyu** [comment]
这个错误是哪里报出来的？是运行的脚本还是 web 服务器？如果是脚本请将上下文的日志也贴上来，如果是 web 服务器请将你的 web 服务器配置文件贴出来

**Comment by Jaggle** [comment]
是我修改ssl_certificate和ssl_certificate_key后重启nginx后出来的：

`sudo /usr/local/nginx/sbin/nginx -s reload
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/root/proj/xdtianyu/account.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)`

**Comment by xdtianyu** [comment]
证书对配错了， 请仔细阅读 [README](https://github.com/xdtianyu/scripts/blob/master/lets-encrypt/README-CN.md)
最后生成的 `example.chained.crt ` 是证书文件， `example.com.key` 是私钥。

一个参考配置
```
server_name  lets-encrypt.xdty.org;
ssl_certificate certs/letsencrypt.chained.crt;
ssl_certificate_key certs/letsencrypt.key;
```
