### ISSUE TITLE
python 报错

### ISSUE THREAD

**Issue by zouhua** [xdtianyu/scripts#21]
Generate CSR...app-test.csr
Traceback (most recent call last):
  File "/tmp/acme_tiny.py", line 2, in <module>
    import argparse, subprocess, json, os, sys, base64, binascii, time, hashlib, re, copy, textwrap, logging
ImportError: No module named argparse

**Comment by xdtianyu** [comment]
是什么系统？Python是什么版本？参考这里 http://stackoverflow.com/questions/15093444/importerror-no-module-named-argparse
