### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by laifuer** [xdtianyu/scripts#24]
Generate account key...
Generating RSA private key, 4096 bit long modulus
......................................++
.................................................++
e is 65537 (0x10001)
Generate domain key...
Generating RSA private key, 2048 bit long modulus
.........................+++
........................................................+++
e is 65537 (0x10001)
Generate CSR...mrluo.csr
Parsing account key...
Parsing CSR...
Registering account...
Registered!
Verifying mrluo.pw...
Traceback (most recent call last):
  File "/tmp/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/tmp/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/tmp/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to /home/wwwroot/mrluo.pw/.well-known/acme-challenge/4NioLXi0m0egqi20mTZl3ELheqychV1ZX_kTDC36zX4, but couldn't download http://mrluo.pw/.well-known/acme-challenge/4NioLXi0m0egqi20mTZl3ELheqychV1ZX_kTDC36zX4 @

**Comment by xdtianyu** [comment]
需要已经绑定域名到 /var/www/example.com 目录，即通过 http://example.com http://whatever.example.com 可以访问到 /var/www/example.com 目录，用于域名的验证

**Comment by laifuer** [comment]
已经绑定了啊 我用的lnmp

/home/wwwroot/域名

**Comment by laifuer** [comment]
是有什么地方需要设置权限吗

**Comment by xdtianyu** [comment]
试下手动新建个文件夹 .wellxxx，里边放个test.txt，在浏览器看看能访问吗？

laifuer <notifications@github.com>于2016年7月3日星期日 12:05写道：

**Comment by laifuer** [comment]
用root还是ftp？

**Comment by xdtianyu** [comment]
都行吧

laifuer <notifications@github.com>于2016年7月3日星期日 12:12写道：

**Comment by laifuer** [comment]
403

**Comment by laifuer** [comment]
搞定 lnmp目录权限问题，谢谢

**Comment by boweic** [comment]
请问具体怎么搞定的？

**Comment by xdtianyu** [comment]
@boweic 大概 `chmod -R 755 /var/www` 或者 `chown -R www-data:www-data /var/www` 这样。如果遇到这样基础的问题，先不要着急，仔细在 Google 或 baidu 查找下出错的原因，一点一点解决。

**Comment by boweic** [comment]
多谢！解决了！ Domian-dir 和默认的 var/www 不一样，改成自己的就好了！
