### ISSUE TITLE
脚本在创建目录的时候会有 \r 回车符，导致无法验证域名

### ISSUE THREAD

**Issue by ifsay** [xdtianyu/scripts#3]
我在验证域名的时候总是无法成功验证，然后发现脚本生成的目录有点问题，遂修改了脚本，把脚本第53行的'mkdir -p $DOMAIN_DIR'改成了'mkdir $DOMAIN_DIR'，随后再次运行脚本出现了如下提示：
mkdir: cannot create directory `/home/wwwroot/domain/web\r/.well-known/acme-challenge/': No such file or directory
我认为是\r回车符的原因，但我技术不够高无法解决这个问题，所以在这里求教您。

**Comment by xdtianyu** [comment]
你是按照这个 [README](https://github.com/xdtianyu/scripts/blob/master/lets-encrypt/README-CN.md) 操作的吗？wget 下载，不要修改脚本内容，提示的什么错误？另外把你的conf文件贴一下吧

**Comment by xdtianyu** [comment]
`/home/wwwroot/domain/web\r/` 这个 `\r` 应该是你在配置文件里产生的，注意格式 `DOMAIN_DIR="/var/www/example.com"`

**Comment by ifsay** [comment]
是按照README操作的，不修改脚本内容提示：
Traceback (most recent call last):
  File "/tmp/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/tmp/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/tmp/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
/.well-known/acme-challenge/bsr9RoSg4oQRILoev8-D3L04iMefTPa1U1nlv1P5zW4, but couldn't download http://transnet.xyz/.well-known/acme-challenge/bsr9RoSg4oQRILoev8-D3L04iMefTPa1U1nlv1P5zW4

conf文件如下：
# only modify the values, key files will be generated automaticly.
ACCOUNT_KEY="letsencrypt-account.key"
DOMAIN_KEY="transnet.xyz.key"
DOMAIN_DIR="/home/wwwroot/domain/web"
DOMAINS="DNS:transnet.xyz,DNS:www.transnet.xyz"

感谢！

**Comment by xdtianyu** [comment]
你手动新建一个  `/home/wwwroot/domain/web/.well-known/acme-challenge/`目录，在里边放一个文件如 `test.txt`，内容随便填一些，然后通过浏览器访问 `http://transnet.xyz/.well-known/acme-challenge/test.txt` 看能不能正常访问到这个文件。如果不能，要先配置你的Web服务器让可以正常访问到。

**Comment by ifsay** [comment]
问题已经解决了，麻烦你了~谢谢~
