### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by boweic** [xdtianyu/scripts#32]
Traceback (most recent call last):
  File "/tmp/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/tmp/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/tmp/acme_tiny.py", line 104, in get_crt
    raise ValueError("Error requesting challenges: {0} {1}".format(code, result))
ValueError: Error requesting challenges: 500 {
  "type": "urn:acme:error:serverInternal",
  "status": 500

不是很懂，总之https失效了

**Comment by xdtianyu** [comment]
`urn:acme:error:serverInternal` 应该是 `Let's encrypt` 服务器那边偶然出错了吧，重试下还是这样的结果吗？

**Comment by boweic** [comment]
是的确实如此，试了几次终于成功了，看了他们的status board 发现现在确实有问题。谢谢了。

**Comment by xdtianyu** [comment]
感谢反馈~
