### ISSUE TITLE
nginx centos6.6 

### ISSUE THREAD

**Issue by kaixulucky** [xdtianyu/scripts#35]
[root@hjl10001 ]#./le-dnspod.sh dnspod.conf 
# INFO: Using main config file dnspod.conf

To use dehydrated with this certificate authority you have to agree to their terms of service which you can find here: https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf

To accept these terms of service run `./letsencrypt.sh --register --accept-terms`.
# INFO: Using main config file dnspod.conf
+ Generating account key...
+ Registering account key with ACME server...
+ Done!
[root@hjl10001 ]#ll -a
总用量 80
drwxr-xr-x 3 root root  4096 2月  10 16:07 .
drwxr-xr-x 3 root root  4096 2月  10 16:01 ..
drwx------ 3 root root  4096 2月  10 16:03 accounts
-rw-r--r-- 1 root root   194 2月  10 13:13 dnspod.conf
-rwxr-xr-x 1 root root   570 2月  10 16:03 dnspod-hook.sh
-rwxr-xr-x 1 root root  2041 2月  10 16:03 dnspod.sh
-rw-r--r-- 1 root root    79 2月  10 16:02 domains.txt
-rwxr-xr-x 1 root root   925 2月  10 13:10 le-dnspod.sh
-rwxr-xr-x 1 root root 45074 2月  10 16:03 letsencrypt.sh
[root@hjl10001 ]#
这个状态是否正确，但当前目录没有生成certs目录

**Comment by xdtianyu** [comment]
请删除脚本目录下除 `dnspod.conf` 文件外的其他文件和文件夹后，再试下执行下面命令

```
wget https://github.com/xdtianyu/scripts/raw/master/le-dns/le-dnspod.sh
chmod +x le-dnspod.sh
./le-dnspod.sh dnspod.conf
```

**Comment by kaixulucky** [comment]
感谢！我试下

**Comment by kaixulucky** [comment]
谢谢，上个问题已解决，当前目录下已生成:
[root@hjl10001 ]#ll
总用量 8
-rw------- 1 root root 1740 2月  10 16:55 cert-1486716931.csr
-rw------- 1 root root    0 2月  10 16:55 cert-1486716931.pem
-rw------- 1 root root 3243 2月  10 16:55 privkey-1486716931.pem
但是命令执行最后报错：
[root@hjl10001 ]#./le-dnspod.sh dnspod.conf 
# INFO: Using main config file dnspod.conf
+ Generating account key...
+ Registering account key with ACME server...
+ Done!
# INFO: Using main config file dnspod.conf
Processing a.com with alternative names: www.a.com m.a.com mall.a.com oa.a.com
 + Signing domains...
 + Creating new directory ./certs/a.com ...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for a.com...
 + Requesting challenge for www.a.com...
 + Requesting challenge for m.a.com...
 + Requesting challenge for mall.a.com...
ERROR: Problem connecting to server (post for https://acme-v01.api.letsencrypt.org/acme/new-authz; curl returned with 7)

**Comment by xdtianyu** [comment]
这个错误是连接 le 服务器认证时出错了吧，你再试一次或者最好在国外网络环境下操作。

**Comment by kaixulucky** [comment]
thank you very much!!!!!!!!!!!!!!
这会删除其它所有文件只留dnspod.conf le-dnspod.sh两个文件，重新执行，没报任何错了。
