### ISSUE TITLE
如果你把域名 DNS 解析放在国内，这一步很可能会遇到类似这样的错误

### ISSUE THREAD

**Issue by ikingi** [xdtianyu/scripts#36]
![error](https://cloud.githubusercontent.com/assets/25564853/23209892/24427d7c-f936-11e6-825f-e1875dc4d9f0.jpg)

域名使用的ML，
Nameserver 1  ：NS01.FREENOM.COM
Nameserver 2  ：NS02.FREENOM.COM
Nameserver 3  ：NS03.FREENOM.COM
Nameserver 4  ：NS04.FREENOM.COM

DNS解析到东京的机房。。
跑这个命令就出错./letsencrypt.sh letsencrypt.conf
字面解释应该是写入成功，但是禁止访问。如何能处理掉。大佬
SOS大佬！！！！

**Comment by xdtianyu** [comment]
需要等DNS解析生效吧，如果用的 cloudxns或者dnspod的服务，可以试试 dns 认证的方式 https://github.com/xdtianyu/scripts/tree/master/le-dns

**Comment by ikingi** [comment]
@xdtianyu 不是说国内的dns会出现这效果吗。。国外域名服务跟DNS，怎么还会这样？DNS早已解析生效。。。还有什么办法吗。大佬

**Comment by xdtianyu** [comment]
https://github.com/xdtianyu/scripts/issues/37 closed
