### ISSUE TITLE
cloudxns已接管./le-cloudxns.sh cloudxns.conf依然报错

### ISSUE THREAD

**Issue by ikingi** [xdtianyu/scripts#37]
修改 DOMAIN 为你的根域名  （我修改成***.ml）还是报ERROR CONFIG. 这样的错误。

![1](https://cloud.githubusercontent.com/assets/25564853/23211837/e592c286-f93e-11e6-973a-e418f39dda96.jpg)
![2](https://cloud.githubusercontent.com/assets/25564853/23211847/f01e553a-f93e-11e6-85b7-39e507bb6c0e.jpg)
![3](https://cloud.githubusercontent.com/assets/25564853/23211868/0506bc8a-f93f-11e6-9164-e82e3a1dbc40.jpg)
![wenjiancuowu](https://cloud.githubusercontent.com/assets/25564853/23211879/11f1dd3a-f93f-11e6-8de1-c8c32af66186.jpg)

**Comment by xdtianyu** [comment]
```
API_KEY="YOUR_API_KEY"
SECRET_KEY="YOUR_SECRET_KEY"
DOMAIN="example.com"
CERT_DOMAINS="example.com www.example.com im.example.com"
#ECC=TRUE
```
修改 DOMAIN 为你的根域名，修改 CERT_DOMAINS 为您要签的域名列表

**Comment by ikingi** [comment]
DOMAIN="*****.ml"
我也这么修改了。。但是还是同样的错误。

**Comment by xdtianyu** [comment]
请把你完整的 conf 文件内容贴出来吧

**Comment by ikingi** [comment]
大佬，有联系方式吗。。。。

**Comment by xdtianyu** [comment]
`ERROR CONFIG.` 这个错误是找不到配置文件的提示，请 `cat cloudxns.conf` 看看有没有这个文件及内容是否正确，另外你上文截图里的配置明显不对， `DOMAIN` 为什么会是路径地址？

**Comment by alstarking** [comment]
已解决。谢谢大佬。正常申请证书报错应该是lnmp1.3的Nginx默认是访问不到.well-known/acme-challenge，将Nginx的
location ~ /\.
{
deny all;
}
修改成
location ~ /.well-known {
allow all;
}

就解决了。。刚装了lnmp1.4测试版，这个问题已经不存在了。。lnmp1.4里已经默认加入了/.well-known

**Comment by xdtianyu** [comment]
感谢反馈～

**Comment by tang1989324** [comment]
@alstarking lnmp1.3的Nginx的默认配置在哪 我改了还是不行

**Comment by ikingi** [comment]
@tang1989324 /usr/local/nginx/conf/vhost/**.conf

**Comment by hifer** [comment]
ValueError: Wrote file to /data/frontend/.well-known/acme-challenge/VR99TFl4_cSituBUJ310UgeHpS9fwC4oB5GKvjh7LGc, but couldn't download http://test.cscec3b.com.cn/.well-known/acme-challenge/VR99TFl4_cSituBUJ310UgeHpS9fwC4oB5GKvjh7LGc
[root@localhost certs]# ll /data/frontend/.well-known/acme-challenge/VR99TFl4_cSituBUJ310UgeHpS9fwC4oB5GKvjh7LGc
-rw-r--r--. 1 root root 87 May 19 13:26 /data/frontend/.well-known/acme-challenge/VR99TFl4_cSituBUJ310UgeHpS9fwC4oB5GKvjh7LGc

大神，这个文件写进去了 但是还是报down不下来

**Comment by xdtianyu** [comment]
@hifer 试下手动新建个文件在浏览器打开，下载不下来就说明 web 服务器配置有问题

**Comment by hifer** [comment]
手动在浏览器上是能下载下来的

**Comment by xdtianyu** [comment]
@hifer 可以再试下，可能是 le 的服务器访问国内托管的文件时下载失败了

**Comment by hifer** [comment]
@xdtianyu 
Generate CSR...test.csr
Parsing account key...
Parsing CSR...
Registering account...
Traceback (most recent call last):
  File "/tmp/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/tmp/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/tmp/acme_tiny.py", line 92, in get_crt
    raise ValueError("Error registering: {0} {1}".format(code, result))
ValueError: Error registering: 500 {
  "type": "urn:acme:error:serverInternal",
  "detail": "Failed to get registration by key",
  "status": 500
}

**Comment by xdtianyu** [comment]
@hifer 这个错 500 误是 le 服务器返回的。如果是使用的 cloudxns 托管的 dns，也可以试试用 dns 验证的方式签发证书 https://github.com/xdtianyu/scripts/tree/master/le-dns

**Comment by hifer** [comment]
@xdtianyu 好的，等会试下，多谢了
