### ISSUE TITLE
希望可以支持cloudflare

### ISSUE THREAD

**Issue by chancat87** [xdtianyu/scripts#38]
作者能否增加cloudflare的支持呀

**Comment by xdtianyu** [comment]
为什么不用 cloudflare 免费 https cdn 呢？

**Comment by daiaji** [comment]
@xdtianyu 我也希望le-dns加入cloudflare的支持……
事实上cloudflare的Flexible SSL对webdav支持不好……
假如PVS上用http webdav cloudflare上用Flexible SSL webdav客户端容易报错
但是cloudflare的Full SSL (strict)没问题（VPS也用https
cloudxns这贱种居然封停了我的域名解析……
干TM的
