### ISSUE TITLE
cloudxns ddns脚本运行出错

### ISSUE THREAD

**Issue by niclau** [xdtianyu/scripts#4]
已确保conf填写正确，已在cloudxns上填写相应subdomain A记录
root@OpenWrt:~/ddns# ./cloudxns.sh cloudxns.conf 
DOMAIN ID: 53193 334499
RECORD ID: 
Invalid API request, may be your URL path error, please check your URL, and then try again.
Fri Jan  1 10:10:12 HKT 2016 -- Update failed

**Comment by xdtianyu** [comment]
从 `DOMAIN ID` 看有两个域名，而查询 `RECORD ID`即子域名没有查询到

**Comment by xdtianyu** [comment]
能不能提供下你的两个域名是什么我检查下脚本，可能因为字符重叠没有过滤掉

**Comment by niclau** [comment]
我的conf下只有一个域名，一个纯数字的.net
API_KEY="x"
SECRET_KEY="x"
DOMAIN="334499.net"
HOST="ap"
LAST_IP_FILE="/tmp/.LAST_IP"

**Comment by xdtianyu** [comment]
cloudxns里边是不是绑定了另一个字符类似的域名？

**Comment by niclau** [comment]
@xdtianyu 没有，另外的域名是全英文的。

**Comment by xdtianyu** [comment]
你是不是用的很久以前的脚本没有更新呢？

在 `DOMAIN_ID=$(curl -k -s $URL_D -H "API-KEY: $API_KEY" -H "API-REQUEST-DATE: $DATE" -H "API-HMAC: $HMAC_D"|grep -o "id\":\"[0-9]*\",\"domain\":\"$DOMAIN"|grep -o "[0-9]*")`行之前增加 
```
echo $(curl -k -s $URL_D -H "API-KEY: $API_KEY" -H "API-REQUEST-DATE: $DATE" -H "API-HMAC: $HMAC_D")
exit 0
```
检查下输出贴一下

**Comment by niclau** [comment]
{"code":1,"message":"success","total":"2","data":[{"id":"13346","domain":"niclau.net.","status":"ok","level":"3","take_over_status":"ok","create_time":"2015-05-04 00:01:00","update_time":"2016-01-01 10:23:44","ttl":"600"},{"id":"53193","domain":"224499.net.","status":"ok","level":"3","take_over_status":"ok","create_time":"2015-12-31 22:28:03","update_time":"2016-01-01 10:09:10","ttl":"600"}]}

**Comment by xdtianyu** [comment]
因为域名是纯数字，过滤时候把域名的数字部分也过滤出来了。稍等我更新下脚本

**Comment by xdtianyu** [comment]
注意删除之前的脚本文件，`wget https://raw.githubusercontent.com/xdtianyu/scripts/master/ddns/cloudxns.sh` 更新下脚本。再试下应该就好了

**Comment by niclau** [comment]
感谢，已更新成功。
PS：对于获取公网IP IP=$(curl -s ip.xdty.org)，可以用dig +short myip.opendns.com @208.67.220.220 -p 443

**Comment by xdtianyu** [comment]
感谢反馈~
