### ISSUE TITLE
py脚本出错，无法创建文件，什么原因的？目录名都创建成功了，但文件没有创建成功，验证失败了

### ISSUE THREAD

**Issue by cfanbo** [xdtianyu/scripts#45]
Verifying blog.abc.com...
Traceback (most recent call last):
  File "/tmp/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/tmp/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/tmp/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to /data/wwwroot/blog.abc.com/.well-known/acme-challenge/_cHNv_NkY5imag1sViV7xXfqLiT2DmpCd， but couldn't download 。。。

**Comment by xdtianyu** [comment]
参考着一个问题 https://github.com/xdtianyu/scripts/issues/37#issuecomment-302613031

**Comment by zhaoyibo** [comment]
我也遇到了这个问题。不过最终发现，并不是文件没有创建，而是创建完被删除了 https://github.com/diafygi/acme-tiny/blob/master/acme_tiny.py#L121
建议你看下 nginx 的错误日志。
我遇到的这个问题是因为我的 nginx 是以 nginx 用户运行的，而相应的 .well-known 文件夹是在 root 目录下，导致 nginx 无权访问，放到 /home/nginx 下就好了。
希望对你能有所帮助。
