### ISSUE TITLE
能不能指定某个文件夹让证书都生成在这个文件夹啊

### ISSUE THREAD

**Issue by daiaji** [xdtianyu/scripts#47]
都放在脚本工作目录 清理起来好麻烦啊

**Comment by xdtianyu** [comment]
可以尝试使用软链接将证书文件从web服务配置目录指向到脚本工作目录的生成文件。

**Comment by daiaji** [comment]
@xdtianyu 我尝试设定ACCOUNT_KEY DOMAIN_KEY为绝对路径
然后证书就直接生成到~目录下了……
更尬了
所以这个是由acme_tiny.py控制的吗？

**Comment by xdtianyu** [comment]
建议直接修改 

```
cat "$DOMAIN_CRT" lets-encrypt-x3-cross-signed.pem > "$DOMAIN_CHAINED_CRT"

if [ "$LIGHTTPD" = "TRUE" ];then
    cat "$DOMAIN_KEY" "$DOMAIN_CRT" > "$DOMAIN_PEM"
```

里 cat 命令 > 后的文件路径。

**Comment by daiaji** [comment]
@xdtianyu 为啥不在配置文件里设定一个相关的键值呢？

**Comment by xdtianyu** [comment]
因为没有考虑过这个需求

**Comment by daiaji** [comment]
@xdtianyu  顺便问一下就是/.well-known/acme-challenge/那个验证用的url默认是http吧
但是我出于能少开端口就少开端口的原则 是弄了全域SSL的 于是80端口就关掉了
acme_tiny.py也是固化了这个url为http吧
这样我就不得不在验证时开启80端口了
这样脚本就需要root的权限了……

只能这样吗？
有办法只开443端口也能完成lets encrypt的续期吗？

**Comment by xdtianyu** [comment]
你试一下吧，我记得 443 端口是可以用于验证的不是必须 80 。而且 443 和 80 端口都需要以 root 权限启动的。脚本不会监听端口吧，是你的 web 服务监听的。另外你可以选择 dns 验证的方式，也不需要验证web目录了只需要改 dns 就可以。更多问题请仔细阅读 README 文档 https://github.com/xdtianyu/scripts/tree/master/le-dns

**Comment by daiaji** [comment]
@xdtianyu ![42-1f52g50200-50 jpg q_80](https://user-images.githubusercontent.com/25875791/27868506-794cabc4-61cf-11e7-8830-d8dd0814c67c.jpg)

**Comment by daiaji** [comment]
@xdtianyu 然后就很奇怪了
为什么le-cloudxns.sh会把生成的签名塞到certs
而letsencrypt.sh不会？
