### ISSUE TITLE
Verifying domain error

### ISSUE THREAD

**Issue by sunjun81** [xdtianyu/scripts#5]
hey guys, i got this exception, does anyone knows why? Thanks in advance!

u'error': {u'type': u'urn:acme:error:connection', u'detail': u'DNS query timed out'}, u'type': u'http-01'}

**Comment by xdtianyu** [comment]
Which dns provider? Please check `nslookup YOUR-DOMAIN 8.8.8.8`

**Comment by sunjun81** [comment]
用的是阿里云的ecs和域名解析。

**Comment by xdtianyu** [comment]
`nslookup 域名 8.8.8.8` 能查询到吗？

**Comment by sunjun81** [comment]
nslookup xxxx.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	xxxx.com
Address: 120.55.111.11

**Comment by xdtianyu** [comment]
参考这里 [DNS query timed out](https://community.letsencrypt.org/t/dns-query-timed-out/5353)，这个应该是dns解析的问题，你可以使用 lets-encrypt  [官方客户端](https://github.com/letsencrypt/letsencrypt)试试应该是一样的结果。切换到国外任何一家dns解析应该就可以了，另外我刚才测试cloudxns是正常的。
