### ISSUE TITLE
文档可否完善下

### ISSUE THREAD

**Issue by baiyuxiong** [xdtianyu/scripts#6]
1、这四个参数都表示什么意思？ 

ACCOUNT_KEY="letsencrypt-account.key" 
DOMAIN_KEY="example.com.key" 
DOMAIN_DIR="/var/www/example.com" 
DOMAINS="DNS:example.com,DNS:whatever.example.com"

2、为什么没有 fullchain.pem 和 privkey.pem ？ 
nginx 应该怎么配置？

3、脚本必须放在/etc/nginx/certs目录下吗？

谢谢

**Comment by xdtianyu** [comment]
这些都可以顾名思义，参考 [README-CN](https://github.com/xdtianyu/scripts/blob/master/lets-encrypt/README-CN.md)

`ACCOUNT_KEY` 表示用于 lets-encrypt 的用户证书，表示你个人的身份
`DOMAIN_KEY` 是你申请域名的 HTTPS 证书私钥
`DOMAIN_DIR` 是网站目录
`DOMAINS` 是你的几个域名或二级域名

生成的文件 `*chained*` 就是你的` fullchain.pem`，你配置的 `example.com.key` 就是 `privkey.pem`，nginx 如何配置这个可以自行 Google 百度。这些内容已经超越了这个脚本的目的，有基础的人可以很轻松搞定这些。

**Comment by gamefriends** [comment]
一台机器有多个站，例如：
www.domain.com 对应->  /home/wwwroot/www.domian.com
static.domain.com 对应-> /home/wwwroot/static.domain.com

那个DOMAIN_DIR该如何配置呢？
