### ISSUE TITLE
如何在一台机器上配多个站？

### ISSUE THREAD

**Issue by gamefriends** [xdtianyu/scripts#7]
一台机器有多个站，例如：
www.domain.com 对应-> /home/wwwroot/www.domian.com
static.domain.com 对应-> /home/wwwroot/static.domain.com

那个DOMAIN_DIR该如何配置呢？

**Comment by xdtianyu** [comment]
做两个配置文件，脚本运行两次。如果你不愿意这么做，可以临时调整你的web配置，指向到同一个目录。

**Comment by gamefriends** [comment]
了解了，非常感谢。

**Comment by RYAN-JIM** [comment]
脚本运行两次，生成的account.key，domain.key等文件会不会覆盖原先的？

**Comment by xdtianyu** [comment]
@RYAN-JIM 不会覆盖

**Comment by RYAN-JIM** [comment]
折腾了一个下午，用的apache，可用的资料很少，证书是获取了，当配不起来，yum install mod_ssl 结果覆盖文件，导致apache无法启动。现在恢复了，却不敢再折腾了。

我邮箱：joomlavisually{@}gmail.com
可以的话，希望能跟你更好的交流和学习下

官方脚本和acme-tiny都用过，配不起来。

**Comment by xdtianyu** [comment]
@RYAN-JIM 可以参考这里 http://www.freehao123.com/lets-encrypt/

**Comment by RYAN-JIM** [comment]
第一个参考的就是这个，他下面的apache配置是修改至军哥的，是错误的。会导致apache无法启动
证书都已经在/etc/letsencrypt/live/域名.com目录下了。只差正确的配置

**Comment by RYAN-JIM** [comment]
在日本人的网站上看到配置，没测试，不懂的是/var/www/example这个地方是不是要改成站点路径？
<VirtualHost *:443>
   ServerName example.com
   DocumentRoot "/var/www/example"
 
   SSLEngine on
   SSLHonorCipherOrder on
   Header set Strict-Transport-Security "max-age=31536000; includeSubDomains"
   SSLProtocol -All +TLSv1 +TLSv1.1 +TLSv1.2
   SSLCipherSuite HIGH:MEDIUM:!aNULL:!MD5
 
   SSLCertificateFile /etc/letsencrypt/live/example.com/cert.pem
   SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
   SSLCertificateChainFile /etc/letsencrypt/live/example.com/chain.pem
   
    <Directory "/var/www/example">
        Options FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
 
    SetEnvIf Request_URI "\.(gif|jpg|png|css|js)$" nolog
    ErrorLog logs/error_log
    CustomLog logs/access_log combined env=!nolog
</VirtualHost>

**Comment by xdtianyu** [comment]
是的，要改成域名指向的目录。如果有这类问题请先检查下 `apache` 的错误日志，再搜索/思索下是哪里的问题。
