### ISSUE TITLE
生成的密钥关系？

### ISSUE THREAD

**Issue by gamefriends** [xdtianyu/scripts#8]
这个工作非常好用，非常感谢。
letsencrypt-account.key
static.chained.crt
static.crt
static.csr
lets-encrypt-x1-cross-signed.pem
static.miagame.com.key

生成的密钥哪个是公钥，哪个是私钥呢？

是否有完整Nginx配置说明？

**Comment by xdtianyu** [comment]
从你的配置来看，static.crt是公钥， static.miagame.com.key 是私钥。实际需要使用 static.chained.crt 作为证书，这个加入了证书链。static.csr 是申请证书时的中间文件。

Nginx 配置就是正常的 https 配置，网上有很多教程你可以搜下。以下关键几行参考

``` 
    listen       80;
    listen       443 ssl http2;
    server_name  static.miagame.com;
    ssl_certificate certs/static.chained.crt;
    ssl_certificate_key certs/static.miagame.com.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;
```

**Comment by hbrls** [comment]
感谢 lz 的脚本！

由于我使用的是阿里云的 CoreOS，因此做了一个 docker 镜像。[hbrls/letsencrypt](https://hub.docker.com/r/hbrls/letsencrypt/)，README 文件列举了操作的步骤。

假如文档需要增强的话我很乐意帮忙。

**Comment by xdtianyu** [comment]
@hbrls 感谢回馈~欢迎提交更新 README
