### ISSUE TITLE
可否添加一下ECC证书支持？

### ISSUE THREAD

**Issue by SkyLape** [xdtianyu/scripts#9]
似乎很简单。只要把生成私钥的格式改一下就行了。

**Comment by xdtianyu** [comment]
请问是哪一个脚本？

**Comment by FlyGoat** [comment]
Let's Encrypt那个呗。

**Comment by xdtianyu** [comment]
Let's encrypt 有两个。。

**Comment by FlyGoat** [comment]
letsencrypt.sh
这个啊，没看见有第二个。

**Comment by xdtianyu** [comment]
已添加 `ECC` 证书支持，欢迎测试  [https://github.com/xdtianyu/scripts/blob/master/lets-encrypt/README-CN.md](https://github.com/xdtianyu/scripts/blob/master/lets-encrypt/README-CN.md)
